### ISSUE TITLE
INPUT_BUILD_ARGS parsing error

### ISSUE THREAD

**Issue by mattndr** [gperdomor/nx-tools#350]
Dockerfile arguments:
```
ARG NODE_VERSION=undefined
ARG NGINX_VERSION=undefined
```
Command:
`INPUT_BUILD_ARGS=NODE_VERSION=14.17.5,NGINX_VERSION=1.21.3 npx nx run angular:docker`

Error:
`buildx call failed with: error: failed to solve: failed to solve with frontend dockerfile.v0: failed to create LLB definition: failed to parse stage name "node:14.17.5,NGINX_VERSION=1.21.3": invalid reference format
`

**Comment by gperdomor** [comment]
@mattndr in that case, the variables should be spliced by a new line.

### Option 1: Using dotenv
Create a `.env` file in the root of the workspace with this content
```
INPUT_BUILD_ARGS="NODE_VERSION=14.17.5-alpine\nNGINX_VERSION=1.21.3"
```

Take a look of the `\n` between both variables, then run `nx run angular:docker`

### Option 2: Inline execution

Sadly, the string of the first option not work if you try to run `INPUT_BUILD_ARGS="NODE_VERSION=14.17.5-alpine\nNGINX_VERSION=1.21.3" nx run angular:docker`, in this case you need to use a new line instead of `\n` like the below image 

<img width="682" alt="Screen Shot 2021-10-02 at 1 01 11 PM" src="https://user-images.githubusercontent.com/371939/135723980-2b474eb8-0e4b-4900-b86d-e3f3c52c96c0.png">

**Comment by mattndr** [comment]
Thanks @gperdomor
